// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEFKOM3arkz4cBBy-TVtBu-ayv6ELu40s',
    appId: '1:414773432963:web:0b76f05307404e30f781b6',
    messagingSenderId: '414773432963',
    projectId: 'fir-task-5e2ed',
    authDomain: 'fir-task-5e2ed.firebaseapp.com',
    storageBucket: 'fir-task-5e2ed.appspot.com',
    measurementId: 'G-7GTK5XHSZ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYlVHPYfo7oCSV-RYczzdEjSlVbYgz_4c',
    appId: '1:414773432963:android:27d036a644aab791f781b6',
    messagingSenderId: '414773432963',
    projectId: 'fir-task-5e2ed',
    storageBucket: 'fir-task-5e2ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJzVa-dhQOiC2bM1KTHSjfAvYWxXtl3m0',
    appId: '1:414773432963:ios:f26c5159bc18462bf781b6',
    messagingSenderId: '414773432963',
    projectId: 'fir-task-5e2ed',
    storageBucket: 'fir-task-5e2ed.appspot.com',
    iosBundleId: 'com.example.firebasetask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJzVa-dhQOiC2bM1KTHSjfAvYWxXtl3m0',
    appId: '1:414773432963:ios:f26c5159bc18462bf781b6',
    messagingSenderId: '414773432963',
    projectId: 'fir-task-5e2ed',
    storageBucket: 'fir-task-5e2ed.appspot.com',
    iosBundleId: 'com.example.firebasetask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEFKOM3arkz4cBBy-TVtBu-ayv6ELu40s',
    appId: '1:414773432963:web:cf2e6ed22d03b27ef781b6',
    messagingSenderId: '414773432963',
    projectId: 'fir-task-5e2ed',
    authDomain: 'fir-task-5e2ed.firebaseapp.com',
    storageBucket: 'fir-task-5e2ed.appspot.com',
    measurementId: 'G-L8RXQM77QG',
  );
}
