name: firebasetask
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  firebase_auth: ^5.1.0
  firebase_core: ^3.1.0
  fluttertoast: ^8.2.6
  http: ^1.2.1
  flutter_secure_storage: ^9.2.2
  provider: ^6.1.2
  cloud_firestore: ^5.1.0
  intl: ^0.19.0
  file_picker: ^8.0.5
  firebase_storage: ^12.1.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
